// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/workspace/my-github-workerspace/xyan-workspace/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-react@4.0.76_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from 'D:/workspace/my-github-workerspace/xyan-workspace/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-react@4.0.76_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/workspace/my-github-workerspace/xyan-workspace/node_modules/.pnpm/registry.npmmirror.com+umi@4.0.76_@babel+core@7.22.10_@types+node@20.4.7_@types+react@18.2.20_nmwtkfetyivccoz5lioaifj5za/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
export const useServerInsertedHTML: Function = () => {};
// plugins
export { getSketchJSON } from 'D:/workspace/my-github-workerspace/xyan-workspace/packages/react-components/.dumi/tmp/plugin-html2sketch';
// plugins types.d.ts
