// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/workspace/my-github-workerspace/xyan-workspace/node_modules/.pnpm/registry.npmmirror.com+dumi@2.2.6_@babel+core@7.22.10_@types+node@20.4.7_@types+react@18.2.20_3uqhc2sm4acqhjqdicf5niz44e/node_modules/dumi/theme-default/slots/PreviewerActionsExtra/index.js';
